// cromwell_local.conf
// Local Cromwell backend is intentional here because Nextflow already runs each sample as a Slurm job.
// This avoids nested Slurm submission for each WDL task.

include required(classpath("application"))

backend {
  default = "Local"

  providers {
    Local {
      actor-factory = "cromwell.backend.impl.sfs.config.ConfigBackendLifecycleActorFactory"

      config {
        runtime-attributes = """
        Int cpu = 1
        Int cpus = 1
        Int memory_mb = 5120
        Int memory = 5120
        Int disks = 10
        Int runtime_minutes = 1440
        String? queue
        String? docker
        Int? preemptible
        """

        submit = """
        /bin/bash ${script}
        """

        submit-docker = """
        /bin/bash ${script}
        """

        kill = """
        true
        """

        kill-docker = """
        true
        """

        filesystems {
          local {
            localization: [
              "hard-link", "soft-link", "copy"
            ]

            caching {
              duplication-strategy: [
                "hard-link", "soft-link", "copy"
              ]
            }
          }
        }
      }
    }
  }
}

database {
  profile = "slick.jdbc.HsqldbProfile$"
  db {
    driver = "org.hsqldb.jdbcDriver"
    url = "jdbc:hsqldb:mem:cromwell;db_close_delay=-1;hsqldb.tx=mvcc"
  }
}
