// cromwell.conf

include required(classpath("application"))

backend {
  default = "Slurm"
  providers {
    Slurm {
      actor-factory = "cromwell.backend.impl.sfs.config.ConfigBackendLifecycleActorFactory"

      config {
        filesystems {
          local {
            localization: [ "soft-link", "copy" ]
          }
        }

        runtime-attributes = """
        String? queue
        Int cpus
        Int memory
        Int runtime_minutes
        """
        submit = """
          ./sbatch_throttle.sh -J ${job_name} -D ${cwd} -o ${out} -e ${err} -t ${runtime_minutes} ${if defined(queue) && queue != "" then "-p " + queue else ""} -c ${cpus} --mem=${memory}M --wrap "module load Java/21.0.2; export PATH=/home/lt692/.conda/envs/bio_pipeline_env/bin:\$PATH; exec /bin/bash ${script}"
        """
        
        kill = "scancel ${job_id}"
        check-alive = "squeue -j ${job_id}"
        job-id-regex = "Submitted batch job (\\d+).*"
      }
    }
  }
}

database {
  profile = "slick.jdbc.HsqldbProfile$"
  db {
    driver = "org.hsqldb.jdbcDriver"
    url = "jdbc:hsqldb:mem:cromwell;db_close_delay=-1;hsqldb.tx=mvcc"
  }
}