#!/usr/bin/env bash
#SBATCH --job-name=NUMT_Discovery
#SBATCH --cpus-per-task=1
#SBATCH --mem=2G
#SBATCH --time=24:00:00
#SBATCH --output=log_numt/numt_%j.log

set -euo pipefail

# Submit NUMT discovery between preprocessing and round 1.
# Required environment variables:
#   FULL_SAMPLE_LIST, PRE_OUTPUT_DIR, GLOBAL_REF_DIR,
#   NUCLEAR_ONLY_REF_DIR, REF_DIR, DISCOVERY_OUTROOT, BESTHIT_OUTDIR
# Optional:
#   BATCH_SIZE (accepted for launch_pipeline_all.sh interface consistency; NUMT array remains per-sample)
#   CONCURRENT_BATCHES (default: 2; used as CONCURRENT fallback)
#   CONCURRENT (defaults to CONCURRENT_BATCHES)
#
# Reference notes:
#   GLOBAL_REF_DIR is the whole-genome reference directory.
#   REF_DIR is the chrM reference directory.
#   NUCLEAR_ONLY_REF_DIR must contain references that exclude chrM.
#   GLOBAL_REF_DIR, NUCLEAR_ONLY_REF_DIR, and REF_DIR must already have the
#   indexes required by numt_detection, including bwa index files and samtools
#   faidx indexes.

FULL_SAMPLE_LIST="${FULL_SAMPLE_LIST:?Set FULL_SAMPLE_LIST to the sample TSV used by preprocessing/round1}"
PRE_OUTPUT_DIR="${PRE_OUTPUT_DIR:?Set PRE_OUTPUT_DIR to preprocessing output root}"
# When submitted with sbatch, Slurm may execute a spool copy of this script.
# Prefer the original submission directory when it looks like this repository
# checkout so the bundled numt_detection directory is used consistently.
if [[ -n "${SLURM_SUBMIT_DIR:-}" && -d "${SLURM_SUBMIT_DIR}/numt_detection" ]]; then
  SCRIPT_DIR="$(cd "${SLURM_SUBMIT_DIR}" && pwd)"
else
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
fi
NUMT_DIR="${SCRIPT_DIR}/numt_detection"
GLOBAL_REF_DIR="${GLOBAL_REF_DIR:?Set GLOBAL_REF_DIR to whole-genome reference directory}"
NUCLEAR_ONLY_REF_DIR="${NUCLEAR_ONLY_REF_DIR:?Set NUCLEAR_ONLY_REF_DIR to nuclear-only reference directory}"
REF_DIR="${REF_DIR:?Set REF_DIR to chrM reference directory}"
DISCOVERY_OUTROOT="${DISCOVERY_OUTROOT:?Set DISCOVERY_OUTROOT for NUMT discovery outputs}"
BESTHIT_OUTDIR="${BESTHIT_OUTDIR:?Set BESTHIT_OUTDIR for high-confidence NUMT BED outputs}"
BATCH_SIZE="${BATCH_SIZE:-1}"
CONCURRENT_BATCHES="${CONCURRENT_BATCHES:-2}"
CONCURRENT="${CONCURRENT:-${CONCURRENT_BATCHES}}"
NF_CONFIG_FILE="${NF_CONFIG_FILE:-nextflow.config}"

[[ -d "${NUMT_DIR}" ]] || { echo "ERROR: bundled numt_detection directory does not exist: ${NUMT_DIR}" >&2; exit 1; }
[[ -f "${FULL_SAMPLE_LIST}" ]] || { echo "ERROR: FULL_SAMPLE_LIST does not exist: ${FULL_SAMPLE_LIST}" >&2; exit 1; }
mkdir -p log_numt "${DISCOVERY_OUTROOT}" "${BESTHIT_OUTDIR}"

safe_batch_id="${BATCH_ID:-batch}"
safe_batch_id="${safe_batch_id//[^A-Za-z0-9_.-]/_}"
clean_samples="$(mktemp "${DISCOVERY_OUTROOT}/numt_samples.${safe_batch_id}.${SLURM_JOB_ID:-manual}.$$.XXXXXX.tsv")"

awk -F '	' '
BEGIN { OFS="	" }
{
  gsub(/\r/, "", $0)
}
$0 ~ /^[[:space:]]*$/ { next }
$1 ~ /^#/ { next }
tolower($1) == "sample" { next }
tolower($1) == "sample_id" { next }

NF >= 3 {
  print $1, $2, $3
  next
}

NF == 2 {
  print $1, $2, $2
  next
}

{
  print "ERROR: malformed sample row: " $0 > "/dev/stderr"
  bad=1
}

END {
  if (bad) exit 1
}
' "${FULL_SAMPLE_LIST}" > "${clean_samples}"

if [[ ! -s "${clean_samples}" ]]; then
  echo "ERROR: no valid sample rows after cleaning ${FULL_SAMPLE_LIST}" >&2
  exit 1
fi

missing_numt=0
while IFS=$'\t' read -r sample_id _; do
  if [[ ! -e "${BESTHIT_OUTDIR}/${sample_id}.highconf_numt.bed" ]]; then
    missing_numt=1
    break
  fi
done < "${clean_samples}"

if [[ "${missing_numt}" -eq 0 ]]; then
  echo "INFO: All NUMT high-confidence BED outputs already exist under ${BESTHIT_OUTDIR}; skipping NUMT discovery submission." >&2
  exit 0
fi

auto_config="$(mktemp "${DISCOVERY_OUTROOT}/numt_pipeline.${safe_batch_id}.XXXXXX.config")"

cat > "${auto_config}" <<CONFIG
# Auto-generated by primate_mt_variant_calling/launch_pipeline_numt.sh
SAMPLES_TSV=${clean_samples}
CRAM_ROOT_1=${PRE_OUTPUT_DIR}
CRAM_ROOT_2=${PRE_OUTPUT_DIR}
# numt_detection expects WHOLE_REF_DIR and CHRM_REF_DIR keys in its config.
# Keep the primate_mt_variant_calling launch variables aligned with
# nextflow.config (GLOBAL_REF_DIR and REF_DIR), and map them here at the
# bundled tool boundary.
WHOLE_REF_DIR=${GLOBAL_REF_DIR}
NUCLEAR_ONLY_REF_DIR=${NUCLEAR_ONLY_REF_DIR}
CHRM_REF_DIR=${REF_DIR}
DISCOVERY_OUTROOT=${DISCOVERY_OUTROOT}
BESTHIT_OUTDIR=${BESTHIT_OUTDIR}
CONFIG

echo "INFO: BATCH_ID=${BATCH_ID:-unset}" >&2
echo "INFO: NF_CONFIG_FILE=${NF_CONFIG_FILE} (accepted for chained launcher consistency; NUMT uses its generated --config file)" >&2
echo "INFO: FULL_SAMPLE_LIST=${FULL_SAMPLE_LIST}" >&2
echo "INFO: Clean sample TSV: ${clean_samples}" >&2
echo "INFO: Auto config: ${auto_config}" >&2
echo "INFO: DISCOVERY_OUTROOT=${DISCOVERY_OUTROOT}" >&2
echo "INFO: BESTHIT_OUTDIR=${BESTHIT_OUTDIR}" >&2
echo "INFO: First rows of clean sample TSV:" >&2
head -n 10 "${clean_samples}" >&2

cd "${NUMT_DIR}"
[[ -f submit_numt_end2end_array.sh ]] || { echo "ERROR: Missing submit_numt_end2end_array.sh in ${NUMT_DIR}" >&2; exit 1; }

echo "INFO: Wrote NUMT auto config: ${auto_config}" >&2
echo "INFO: NUMT discovery uses one sample per array task; BATCH_SIZE=${BATCH_SIZE} is accepted for shared launcher configuration but not used for batching." >&2
echo "INFO: Submitting NUMT discovery with CONCURRENT=${CONCURRENT} sample tasks." >&2
CONFIG="${auto_config}"
# Round 1 NUMT consensus filtering defaults to --hc_dp_lower_bound 10 in nextflow.config.
env -u SLURM_SUBMIT_DIR \
    -u SLURM_ARRAY_TASK_ID \
    -u SLURM_ARRAY_JOB_ID \
    -u SLURM_ARRAY_TASK_COUNT \
    -u SLURM_ARRAY_TASK_MIN \
    -u SLURM_ARRAY_TASK_MAX \
  bash submit_numt_end2end_array.sh \
    --config "${CONFIG}" \
    --concurrent "${CONCURRENT}"
